export const GET_WORK_ORDERS = 'GET_WORK_ORDERS';
export const FETCH_ORDERS_SUCCESS = 'FETCH_ORDERS_SUCCESS';
export const FETCH_ORDERS_FAILED = 'FETCH_ORDERS_FAILED';
export const CHANGE_SORT_ORDER = 'CHANGE_SORT_ORDER';
export const SORT_DATA = 'SORT_DATA';
export const CHANGE_SEARCH_PARAM = 'CHANGE_SEARCH_PARAM';
export const FILTER_BY_SEARCH_PARAM = 'FILTER_BY_SEARCH_PARAM';
export const FETCH_ORDERS_START = 'FETCH_ORDERS_START'
